### ISSUE TITLE
creating the .txt file should be an option

### ISSUE THREAD

**Issue by cdrani** [rajdeepbharati/poirot#7]
Right now a __.txt__ file is created regardless of if you want it or not. Some users might not want that considering that the data displayed on the terminal is the same as that in the file. If users want the file they should indicate it by the use of a flag or something.

**Comment by rajgoesout** [comment]
@cdrani Would you like to work on this issue?

**Comment by cdrani** [comment]
Sure. This is reliant on #8 fix. Will apply that fix here as well. Also noticed that you don't actually make use of yargs package here at all. In the fix for this issue I plan on just using the arg values from `process`. Were you planning on making use of it for more than just the help and version options?

**Comment by rajgoesout** [comment]
Yes, we can use yargs package for solving this issue

**Comment by cdrani** [comment]
I am saying that since you are not actually using yargs other than for --help and --version, then perhaps you can remove it and just implement those options.

**Comment by rajgoesout** [comment]
I'm planning to add more command line arguments/features. That's why I've kept it.

**Comment by cdrani** [comment]
Ok. Will keep.
